sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t aalmeida/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aalmeida/docker-react npm run test